### ISSUE TITLE
How to enable for all searches?

### ISSUE THREAD

**Issue by specter78** [arnemart/SafariKeywordSearch#11]
I would like to use specific search engine for all searches and no other. How to send all searches to that url without using keywords?

**Comment by m-schmitt** [comment]
The previous (non-extension) version of Safari Keyword Search had that feature: you could designate one of the keywords as the default.

But I see the difficulty here. Safari isn't notifying the extension that a user is trying to search for something, i.e. it doesn't get control before the keywords are expanded into a URL. SKS is instead scanning each URL, looking to see if it is a "search" URL (e.g. it is for google or something). Then it looks for a keyword.

The point here is that SKS doesn't do anything if it doesn't find the keyword, _on purpose_. If it did, then you wouldn't be able to use Google (or whatever site you've set in Safari as the search site) at all, because all the URLs would be turned into keyword searches.

The only way to get a default search to work is if Safari's search URL was unique and SKS scanned for that exact URL (aside from the search parms).

(I too wish there was a default option. I used to use SKS to set it so that a keyword search would do a Google Browse By Name search instead of always stopping at the Google search results page.)

**Comment by arnemart** [comment]
Yeah with the way the extension API works right now I don't want to add this feature, but it may return in the future.

**Comment by kennymc-c** [comment]
If I understood @m-schmitt correctly, a default search without a keyword would work if you sacrifice the configured safari search engine for it. I think some would be willing to replace less known engines like Ecosia with a default search engine like startpage.com. If necessary, the extension can be deactivated temporarily. If the consequences are explained in the extension this should not be a big problem? Or have I misunderstood something?

**Comment by Jip-Hop** [comment]
I'd be willing to sacrifice the default configured search engine to be able to use searxng as my default search engine :)

Edit:

From [the readme](https://github.com/arnemart/SafariKeywordSearch#weird-detailslimitations-etc):

> In some cases, **the default search engine will load** in the tab before the extension is triggered, especially if the search engine you are using is slightly slow to respond (Wikipedia I'm lookin at you).

For privacy purposes, I think SafariKeywordSearch could go a step further and actually block (with content blocking) the default search engine outright, so this can no longer happen (search queries slipping through to one of Apples allowed search engines).

**Comment by kennymc-c** [comment]
This feature has been added in the latest version (see #29)
