### ISSUE TITLE
Keyword Search Settings

### ISSUE THREAD

**Issue by bengreeno** [arnemart/SafariKeywordSearch#18]
It would be nice to be able to adjust the settings for Keyword Search (macOS) in either the application or the Safari toolbar button. I personally like to hide extension buttons in the Safari toolbar whenever possible. Have the settings in the app would allow me to adjust them there instead of adding Keyword Search back to the Safari toolbar whenever I need to adjust the settings.

All that said... great app!

**Comment by arnemart** [comment]
I may be able to reuse the UI from the settings popover and include it in the app somehow, I'll look into that at some point. if that's not possible however, I don't think I'm going to implement three different UIs for the same thing, especially since native Mac/iOS development really isn't in my core skillset. Thanks for the suggestion though, glad you are liking the app despite this change.
